import { useState } from 'react';
import axios from 'axios';
import './ConvertToNewsModal.css';

const ConvertToNewsModal = ({ post, onClose, onSuccess }) => {
    const [formData, setFormData] = useState({
        title: '',
        content: '',
        category: 'success_story'
    });
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [autoGenerated, setAutoGenerated] = useState(null);

    const handleConvert = async () => {
        try {
            setLoading(true);
            setError('');

            const token = localStorage.getItem('token');

            const response = await axios.post(
                `http://66.94.120.78:7003/api/news/from-post/${post._id}`,
                formData,
                {
                    headers: { Authorization: `Bearer ${token}` }
                }
            );

            setAutoGenerated(response.data.autoGenerated);
            setFormData({
                title: response.data.autoGenerated.title,
                content: response.data.autoGenerated.content,
                category: 'success_story'
            });

            alert('✅ Post converted to news successfully!');
            onSuccess();

        } catch (err) {
            console.error('Error converting to news:', err);
            if (err.response?.data?.message) {
                setError(err.response.data.message);
            } else {
                setError('Failed to convert post to news');
            }
        } finally {
            setLoading(false);
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();

        if (!formData.title.trim() || !formData.content.trim()) {
            setError('Title and content are required');
            return;
        }

        await handleConvert();
    };

    const handleAutoFill = async () => {
        try {
            setLoading(true);
            const token = localStorage.getItem('token');

            // Call the endpoint to get auto-generated content
            const response = await axios.post(
                `http://66.94.120.78:7003/api/news/from-post/${post._id}`,
                { category: formData.category },
                {
                    headers: { Authorization: `Bearer ${token}` }
                }
            );

            if (response.data.autoGenerated) {
                setFormData({
                    ...formData,
                    title: response.data.autoGenerated.title,
                    content: response.data.autoGenerated.content
                });
            }

            setLoading(false);
        } catch (err) {
            console.error('Error auto-filling:', err);
            setError(err.response?.data?.message || 'Failed to auto-fill');
            setLoading(false);
        }
    };

    return (
        <div className="modal-overlay" onClick={onClose}>
            <div className="modal-content" onClick={(e) => e.stopPropagation()}>
                <div className="modal-header">
                    <h2>📰 Convert to News Article</h2>
                    <button className="close-btn" onClick={onClose}>×</button>
                </div>

                {/* Post Preview */}
                <div className="post-preview">
                    <h3>Original Report</h3>
                    <div className="preview-grid">
                        <div className="preview-item">
                            <span className="preview-label">Location:</span>
                            <span className="preview-value">{post.city}, {post.state}</span>
                        </div>
                        <div className="preview-item">
                            <span className="preview-label">Danger Level:</span>
                            <span className="preview-value danger-badge">{post.dangerLevel}/100</span>
                        </div>
                        <div className="preview-item">
                            <span className="preview-label">Type:</span>
                            <span className="preview-value">{post.type.toUpperCase()}</span>
                        </div>
                        <div className="preview-item">
                            <span className="preview-label">Date:</span>
                            <span className="preview-value">
                                {new Date(post.createdAt).toLocaleDateString()}
                            </span>
                        </div>
                    </div>
                    {post.type === 'text' && (
                        <div className="preview-content">
                            <span className="preview-label">Content:</span>
                            <p>{post.content}</p>
                        </div>
                    )}
                </div>

                {error && (
                    <div className="error-message">
                        ⚠️ {error}
                    </div>
                )}

                {/* News Form */}
                <form onSubmit={handleSubmit} className="news-form">
                    <div className="form-actions-top">
                        <button
                            type="button"
                            className="auto-fill-btn"
                            onClick={handleAutoFill}
                            disabled={loading}
                        >
                            ✨ Auto-Fill from Report
                        </button>
                    </div>

                    <div className="form-group">
                        <label>Title *</label>
                        <input
                            type="text"
                            value={formData.title}
                            onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                            placeholder="Enter news article title"
                            required
                        />
                    </div>

                    <div className="form-group">
                        <label>Content *</label>
                        <textarea
                            value={formData.content}
                            onChange={(e) => setFormData({ ...formData, content: e.target.value })}
                            placeholder="Enter news article content"
                            rows={10}
                            required
                        />
                        <div className="char-count">
                            {formData.content.length} characters
                        </div>
                    </div>

                    <div className="form-group">
                        <label>Category</label>
                        <select
                            value={formData.category}
                            onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                        >
                            <option value="success_story">Success Story</option>
                            <option value="general">General News</option>
                        </select>
                    </div>

                    <div className="form-actions">
                        <button
                            type="button"
                            className="cancel-btn"
                            onClick={onClose}
                            disabled={loading}
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            className="submit-btn"
                            disabled={loading}
                        >
                            {loading ? 'Converting...' : '📰 Create News Article'}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default ConvertToNewsModal;
